[env]
account = "1234567890"  # TODO
region = "us-east-1"
name = "dev"
type = "dev"

[secrets]
admin_user = "my/admin"
creds = "my/user"

[s3]
bucket_name = "my-test-bucket-dev"  # TODO
upload_path = "uploads"

[vpc]
id = "vpc-a1234567"
security_group_id = "sg-0123"
