[env]
account = "9876543210"  # TODO
region = "us-east-1"
name = "prod"
type = "production"

[secrets]
admin_user = "my/admin"
creds = "my/user"

[s3]
bucket_name = "my-test-bucket-prod"  # TODO
upload_path = "uploads"

[vpc]
id = "vpc-a1234567"
security_group_id = "sg-0123"
