[env]
account = "9876543210"  # TODO
region = "us-east-1"
name = "prod"
type = "production"

[secrets]
admin_user = "my/admin"
creds = "my/user"

[vpc]
id = "vpc-a1234567"
security_group_id = "sg-0123"
